# Generated by Django 5.0.3 on 2024-04-09 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('job_role', models.CharField(max_length=500)),
                ('qa', models.TextField(default='{"QA": []}')),
                ('is_scheduled', models.BooleanField(default=False)),
                ('result', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('unique_id', models.UUIDField(unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_role', models.CharField(max_length=255, null=True)),
                ('experience', models.CharField(max_length=100, null=True)),
                ('interview_type', models.CharField(max_length=100, null=True)),
                ('interview_completed', models.BooleanField(default=False)),
                ('scheduled_by', models.CharField(default='Admin', max_length=255)),
                ('interview_link', models.URLField(null=True)),
            ],
        ),
    ]
