# Generated by Django 5.0.3 on 2024-03-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleinterview',
            name='experience',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scheduleinterview',
            name='interview_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scheduleinterview',
            name='job_role',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
