# Generated by Django 5.0.3 on 2024-03-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_examplemodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userdata', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('qa', models.TextField(default='{"QA": []}')),
            ],
        ),
    ]
