# Generated by Django 5.0.3 on 2024-03-29 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_yourmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YourModel',
            new_name='InterviewModel',
        ),
    ]
