# Generated by Django 5.0.3 on 2024-03-29 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_rename_yourmodel_interviewmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExampleModel',
            new_name='ScheduleInterview',
        ),
    ]
